resources:
  - ../base

patchesJson6902:
  - path: ./patch-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      replicas: 300
